### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by wdhaun** [rjpcomputing/luaforwindows#106]
Deleted

**Comment by tst2005** [comment]
Hello,

The line prefixed by `--` are comment, then for the runtime the `var1,var2=var3,var4` will just be ignored.

In lua you can have
```lua
a = "a"
b = "b"
```
or
```lua
a, b = "a", "b"
```

The sample just mix some different values
```lua
a,b,c,d,e = 1, 2, "three", "four", 5
```
is equal to
```lua
a = 1
b = 2
c = "three"
d = "four"
e = 5
```

I don't see issue.

**Comment by wdhaun** [comment]
LOL....  Yeah, you are right, I am sorry for the misunderstanding. Please just delete this thread completely.
