### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Tomcat23** [rjpcomputing/luaforwindows#108]
I'm getting an error when installing on Windows 10 x64

The install window says "Installing Microsoft Visual C++ 2005 SP1 Redistributable..."

The popup says unable to execute file
C:Program Files (x86)\Lua\5.1/install/support/vcredist_x86.exe

CreateProcess failed: code 193
%1 is not a valid Win32 application

**Comment by oscarvarto** [comment]
I'm also hitting this issue on Windows 10 x64.

**Comment by idbrii** [comment]
This issue has high google page rank, but it's a dupe of #114.

**Comment by ZhanHui-Xu** [comment]
> I was having a similar problem but disappeared by previously installing
> [http://github.com/rjpcomputing/luaforwindows/releases/download/vc-runtime/vcredist_x86.4053.exe](https://github.com/rjpcomputing/luaforwindows/releases/download/vc-runtime/vcredist_x86.4053.exe)
> as stated here:
> https://github.com/rjpcomputing/luaforwindows#install-notes

thanks.
