### ISSUE TITLE
Update 7zip

### ISSUE THREAD

**Issue by Stanzilla** [rjpcomputing/luaforwindows#109]
Please update your bundled version of 7zip, it is super old and buggy and vulnerable: http://blog.talosintel.com/2016/05/multiple-7-zip-vulnerabilities.html

**Comment by Stanzilla** [comment]
@rjpcomputing is this project still maintained?

**Comment by rjpcomputing** [comment]
It is not abandon, but I have very little time for the project. The project could use some contributor/helps.
