### ISSUE TITLE
404 vc_redistx86

### ISSUE THREAD

**Issue by jcarri** [rjpcomputing/luaforwindows#128]
The link to vcredist_x86.exe on https://code.google.com/archive/p/luaforwindows/ is broken. It returns a 404 error. I think the bigger issue is that this broken link is preventing the installer from working.
Here is the actual link that is broken:
http://luaforwindows.googlecode.com/files/vcredist_x86.exe

**Comment by rjpcomputing** [comment]
You are using an old version of the installer. All links have been moved to GitHub. Please use a release from GitHub.
https://github.com/rjpcomputing/luaforwindows/releases

**Comment by jcarri** [comment]
Thank you. I will send an email to admin of https://www.tutorialspoint.com/lua/lua_environment.htm to let them know this as well. (They are using this project as part of their tutorial for LUA beginners)
