### ISSUE TITLE
Luac creates unix executables, not windows ones

### ISSUE THREAD

**Issue by InternetAstronaut** [rjpcomputing/luaforwindows#144]
I've installed LfW, and tried the luac compiler. But it gave me a .out file (linux and mac) instead of a .exe (windows). If this can't be fixed, could you remove luac so people don't get confused?

**Comment by noobpen** [comment]
![Screenshot 2024-07-20 144857](https://github.com/user-attachments/assets/1a4b9878-ad2d-4208-af33-b94d4b7a95d7)
Screenshot

**Comment by nikitalocalhost** [comment]
> remove luac so people don't get confused?

And what if you need to cross compile from Windows to Linux?

**Comment by InternetAstronaut** [comment]
It could be patched, instead of replaced as well!

**Comment by InternetAstronaut** [comment]
There could also be just `luac` (normal luac) `luac-exe` (exe luac)

**Comment by InternetAstronaut** [comment]
Then we could add a warning in `luac`:
```
This compiles Unix apps, for Windows apps, use luac-exe
```

**Comment by InternetAstronaut** [comment]
I found a program that does what i want! It's called [`rtc`](https://github.com/samyeyo/rtc)

**Comment by InternetAstronaut** [comment]
It even includes a GUI for messing quickly!
![image](https://github.com/user-attachments/assets/506fc442-b6ff-4093-9933-3cb71e4e07d2)

**Comment by InternetAstronaut** [comment]
If you aren't using binary modules, i would recommend the static runtime, since it creates a single `exe`!
