### ISSUE TITLE
Example 37: error loading module 'iuplua' from file 'C:\Program Files (x86)\Lua\5.1\clibs\iuplua51.dll' The specified module could not be found.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rjpcomputing/luaforwindows#22]
```
To reproduce, use Windows 7 64-bit and the LuaForWindows_v5.1.4-40.exe 
installer. Then go to example 37. The following appears:

failed to load & run sample code
error loading module 'iuplua' from file 'C:\Program Files 
(x86)\Lua\5.1\clibs\iuplua51.dll':
        The specified module could not be found.


This kind of breaks the example a little bit, as you can see. See the attached 
log for the full screen output.

I checked out the file. It's definitely there. The file itself doesn't have any 
version information on it. The date modified was 6/25/2010 10:08PM if that 
helps at all.
```

Original issue reported on code.google.com by `nitrod...@gmail.com` on 17 Aug 2010 at 3:26

Attachments:
* [lua_example_37_error.txt](https://storage.googleapis.com/google-code-attachments/luaforwindows/issue-22/comment-0/lua_example_37_error.txt)

**Comment by FabianSilva** [comment]
> ```
> Godamn u ppl, just put another info in the example, "if you launched it from 
> installation this example will not work because the environment variable wasnt 
> set", or something like that
> ```
> Original comment by `yksnimus` on 4 Oct 2012 at 4:08

please advice about restart, as I start learning lua today and doesn't know that it need reboot, I think that something installed wrong, and with a message on examples avoid to think that something was installed wrongly (example 37, external libraries)

**Comment by rogergithubbing** [comment]
Hello, After checking the required paths, I'm still having the same issue
running this code from ZeroBrane studio, from the command line or from SciTE gives the same problem: 

module 'iuplua' not found, or attempt to call a nil value, ... etc.

I have 
LUA_CPATH=C:\Lua5.1\clibs\?.dll;
PATH = C:\Lua5.1;C:\Lua5.1\clibs; ....

USING Lua 5.1 installed from "Lua from windows"

I've already rebooted.

Thanks in advance,

Roger

**Comment by rogergithubbing** [comment]
Fixed the issue reinstalling lua for windows and making sure that my PATH environment variable is not too long... I hope it helps.
