### ISSUE TITLE
Setup unable to acess the directory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rjpcomputing/luaforwindows#46]
```
What steps will reproduce the problem?
1. Anything I checkmark
2. I run
3. It doesn't start

What is the expected output? What do you see instead?
Acess is denited.

What version of the product are you using? On what operating system?
Lua 5.1.4

Please provide any additional information below.
Should I.... log in as admin?
```

Original issue reported on code.google.com by `magerull...@gmail.com` on 26 Aug 2011 at 2:01

**Comment by rjpcomputing** [comment]
I am assuming you are trying to install as a normal user and so you can only write to your user directory. So when it asks for the install directory choose one under your user directory. The installer supports that.
