### ISSUE TITLE
No 5.2 windows binary

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rjpcomputing/luaforwindows#48]
```
"you can get 5.2(beta) from LuaBinaries" - no way :(
```

Original issue reported on code.google.com by `somn.dre...@gmail.com` on 22 Sep 2011 at 11:52

**Comment by rjpcomputing** [comment]
You can't just update Lua to 5.2 and not build and change the module source code to match the breaking changes found in Lua 5.2+. I don't maintain any modules only gathering them together and make a distribution of Lua.

Lua 5.1 is used and will be used until all the modules have been updated.
