### ISSUE TITLE
Missing lua\luasql\ado.lua

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rjpcomputing/luaforwindows#52]
```
require "luasql.ado"

The lua\luasql\ado.lua file is missing from the install.
See luasql distribution : src/ado/ado.lua

```

Original issue reported on code.google.com by `pierrez...@gmail.com` on 4 Dec 2011 at 9:07

**Comment by rjpcomputing** [comment]
It was not built as part of the built binary I got from the module developer. So it was not included. If you build it against Visual Studio 8 I will include it.
