### ISSUE TITLE
Lua 5.2.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rjpcomputing/luaforwindows#61]
```
is there any plans to update to Lua 5.2.1 ?
```

Original issue reported on code.google.com by `shar...@gmail.com` on 13 Aug 2012 at 2:12

**Comment by rjpcomputing** [comment]
You can't just update Lua to 5.2 and not build and change the module source code to match the breaking changes found in Lua 5.2+. I don't maintain any modules only gathering them together and make a distribution of Lua.

Lua 5.1 is used and will be used until all the modules have been updated.
