### ISSUE TITLE
Lua 5.2 not considering to update?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rjpcomputing/luaforwindows#70]
```
Lua 5.2 is release... is there any chance to update this one to the latest 
version? thanks

```

Original issue reported on code.google.com by `laupk...@gmail.com` on 28 Sep 2013 at 4:04

**Comment by rjpcomputing** [comment]
You can't just update Lua to 5.2 and not build and change the module source code to match the breaking changes found in Lua 5.2+. I don't maintain any modules only gathering them together and make a distribution of Lua.

Lua 5.1 is used and will be used until all the modules have been updated.
