### ISSUE TITLE
Update to Lua 5.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rjpcomputing/luaforwindows#78]
```
Binaries need to be updated to 5.2
```

Original issue reported on code.google.com by `maxmorris2001` on 12 Sep 2014 at 1:13

**Comment by rjpcomputing** [comment]
You can't just update Lua to 5.2 and not build and change the module source code to match the breaking changes found in Lua 5.2+. I don't maintain any modules only gathering them together and make a distribution of Lua.

Lua 5.1 is used and will be used until all the modules have been updated.
