### ISSUE TITLE
update to 5.2.3?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rjpcomputing/luaforwindows#79]
```
Im just starting out in LUa 

When will this install be updated to 5.2.3?


What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.

```

Original issue reported on code.google.com by `skibo1...@gmail.com` on 3 Oct 2014 at 10:55

**Comment by rjpcomputing** [comment]
You can't just update Lua to 5.2 and not build and change the module source code to match the breaking changes found in Lua 5.2+. I don't maintain any modules only gathering them together and make a distribution of Lua.

Lua 5.1 is used and will be used until all the modules have been updated.
