### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by le-tuan** [rjpcomputing/luaforwindows#84]
Why it does not support unicode?

**Comment by rjpcomputing** [comment]
Because it is based off Lua 5.1, not Lua 5.3. There is no plan to change that very soon. Maybe there is a Unicode module in LuaRocks you could use.

**Comment by tst2005** [comment]
If you search about pure lua solution you should try : 
* [lua-utf8](https://github.com/tst2005/lua-utf8)
* [lua-utf8-simple](https://github.com/blitmap/lua-utf8-simple)

Else you also should try a full support with : 
 * [luautf8](https://github.com/starwing/luautf8) (luarocks will help you)

There are maybe lot of other solutions...
Regards,
