### ISSUE TITLE
Could you use a newer Lua version?

### ISSUE THREAD

**Issue by Meresmata** [rjpcomputing/luaforwindows#87]
Could you please update Lua to 5.2 or 5.3.     5.1 is laking some features.

**Comment by rjpcomputing** [comment]
You can't just update Lua to 5.2+ and not build and change the module source code to match the breaking changes found in Lua 5.2+. I don't maintain any modules only gathering them together and make a distribution of Lua.

Lua 5.1 is used and will be used until all the modules have been updated.
