### ISSUE TITLE
Add Moses library

### ISSUE THREAD

**Issue by Yonaba** [rjpcomputing/luaforwindows#88]
Hi,

[Moses](http://github.com/Yonaba/Moses) is a utility-belt library, heavily inspired by Javascript's [underscore](http://underscorejs.org) library, which was meant for functional programming in Lua. I just think it will be a nice addition to LuaForWindows.

Regards,
Roland.

**Comment by rjpcomputing** [comment]
Hi,

I would like to try something... Let me know what you think. I would build the installer.

Would you be willing to make a pull request with these additions?

You just place the modules files:
- Documentation: `files/docs/<modulename>/...`
- Binary module: `files/clibs`
- Lua modules: `files/lua`
- Examples: `files/examples/<modulename>/...`
- [Optional] Tools: `files/utils/<modulename>`
