### ISSUE TITLE
Add delaunay library

### ISSUE THREAD

**Issue by Yonaba** [rjpcomputing/luaforwindows#89]
[delaunay](http://github.com/Yonaba/delaunay) is a module for polygon triangulation.
Maybe it would be a good addition to LuaForWindows.

**Comment by rjpcomputing** [comment]
Please make a pull request with these additions?

You just place the modules files:
* Documentation: `files/docs/<modulename>/...`
* Binary module: `files/clibs`
* Lua modules: `files/lua`
* Examples: `files/examples/<modulename>/...`
* [Optional] Tools: `files/utils/<modulename>`
