### ISSUE TITLE
Add strictness

### ISSUE THREAD

**Issue by Yonaba** [rjpcomputing/luaforwindows#90]
[strictness](https://github.com/Yonaba/strictness) is a module for tracking accesses and assignments of undefined variables in Lua. It was designed for Lua 5.0, 5.1 and works for Lua 5.2, in some sense. Would you be interested in adding it to LuaForWindows ?

**Comment by rjpcomputing** [comment]
Please make a pull request with these additions?

You just place the modules files:
* Documentation: `files/docs/<modulename>/...`
* Binary module: `files/clibs`
* Lua modules: `files/lua`
* Examples: `files/examples/<modulename>/...`
* [Optional] Tools: `files/utils/<modulename>`
