### ISSUE TITLE
Add binary-heaps

### ISSUE THREAD

**Issue by Yonaba** [rjpcomputing/luaforwindows#91]
[Binary-Heaps](https://github.com/Yonaba/Binary-Heaps) is a very simple and straight implementation of binary heaps data structure in pure Lua.
Maybe a good addition to LuaForWindows ?

**Comment by rjpcomputing** [comment]
Please make a pull request with these additions?

You just place the modules files:
* Documentation: `files/docs/<modulename>/...`
* Binary module: `files/clibs`
* Lua modules: `files/lua`
* Examples: `files/examples/<modulename>/...`
* [Optional] Tools: `files/utils/<modulename>`
