### ISSUE TITLE
Please add the source-code as used in luaforwindows

### ISSUE THREAD

**Issue by jjvbsag** [rjpcomputing/luaforwindows#93]
This would allow us to support you more in maintaining luaforwindows.

**Comment by rjpcomputing** [comment]
All of the source is included in the GitHub repo now. This is only ever been a distribution of Lua not ever building the binary modules. Those came to the project already pre-built. You just take the module you want included and place the pieces (.dll/.Lua, documentation, examples, etc...) into the correct locations in the project tree. Then use INNO Setup to compile the .issue.

Does this help?

**Comment by jjvbsag** [comment]
Ok, only to get me on the right track: You don't *compile* anything, but only ¹) *collect and combine* binaries/scripts available on the web into one setup?!? 

Then 
* you don't *have* or *use* any sources (in the spell of "ascii files, which can be compiled to binaries")
* my question was misled by false assumptions.

I will refine my issue
"**Please provide a complete list of URLs, where you got the binaries/script from**"


---
¹) Don't get me wrong. The word 'only' shall not undervalue your work. It's a great job done.

**Comment by rjpcomputing** [comment]
Correct.

There is a list in the README.md - https://github.com/rjpcomputing/luaforwindows

Look at the **Libraries Used** section. Please note that the URLs are from when the Libraries were originally added. LuaForge is not around any more so look on GitHub for them as well.
