### ISSUE TITLE
Lua For Windows Installer - 'h' is an invalid URL.

### ISSUE THREAD

**Issue by TheMeq** [rjpcomputing/luaforwindows#98]
Unable to install Lua For Windows as I get this error message during installation. 

'h' is an invalid URL. 

Thanks

**Comment by TheMeq** [comment]
![capture](https://cloud.githubusercontent.com/assets/7303969/10539079/eb5a9f98-73f4-11e5-8066-78f9d4ed623c.PNG)

**Comment by rjpcomputing** [comment]
@TheMeq 

What version did you download? If it is not the latest that could be the problem because it used to be hosted on Google Code and they are shutting that service down and the links in the installer will not be updated to GitHub.

Can you try to download 
http://github.com/rjpcomputing/luaforwindows/releases/download/vc-runtime/vcredist_x86.4053.exe
and place it next to the installer and rerun it.

**Comment by TheMeq** [comment]
I downloaded the one on Google Code and that one worked fine, so I have it installed now. The one I downloaded is the one that is linked within the github readme.md file. 

https://github.com/rjpcomputing/luaforwindows/releases then to https://github.com/rjpcomputing/luaforwindows/releases/download/v5.1.4-49/LuaForWindows_v5.1.4-49.exe

**Comment by rjpcomputing** [comment]
Yes that seems to be the right version. I can not recreate the issue.

What version of Windows are you using?

**Comment by TheMeq** [comment]
I am using Windows 7 Professional

**Comment by AksharaWeave** [comment]
I'm experiencing the exact same issue.  This is on Windows 10 with the latest Lua for Windows version 5.1.4-49 downloaded here from GitHub and with having the vcredist_x86.4053 file in the same directory.  When the installer tries to download a file it pops up the message 'h' is an invalid url.

**Comment by rjpcomputing** [comment]
The issue is coming from building the installer with the Unicode version of INNO Setup. I tried to debug why this issue is occurring and I can't find any help, so I am switching back to the ANSI verions of INNO Setup. Expect a new release soon.

**Comment by rjpcomputing** [comment]
Please test it now.
