### ISSUE TITLE
64 Bit Install option. 

### ISSUE THREAD

**Issue by necrose99** [rjpcomputing/luaforwindows#99]
add option to installer to get Windows X64 versions 
vcredist_x64.exe
 http://www.microsoft.com/en-us/download/details.aspx?id=14431
http://www.microsoft.com/en-us/download/confirmation.aspx?id=14431&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1

http://sourceforge.net/projects/luabinaries/files/5.3/Windows%20Libraries/Dynamic/lua-5.3_Win64_dllw4_lib.zip/download
http://sourceforge.net/projects/luabinaries/files/5.3/Executables/lua-5.3_Win64_bin.zip/download

manually removing lua and artifacts x32 files then overlaying luax64 has seamed to work yet irritating. 
https://github.com/LuaDist/luadist 

anyhow option for 64 bit installs , a script to pull in new versions of packages might be of use. 
and or to pull in new bins  ie update.zip unpack and overwrite.

**Comment by rjpcomputing** [comment]
Thanks for the feedback, but you realize in your issue the difficulty to do this update. So it is not in the current scope of this project to add x64 because the LfW team doesn't build the modules, only collects them into a distribution.

Patches are always accepted.

Moving forward we would like to use LuaDist to build LfW, but just have to make that happen. Would you like to help?

**Comment by necrose99** [comment]
I have no quarrels in testing ,  i've found the modules run fine in 64bit mode... 
just that was the method i used for 'hotwiring ' x64 bit 
mainly manual replacing 32bit core lua files with 64bit  from the SF.net builds. 
LFW works yet still , just packages work in 32/64 mode 

I just meant for the MSI option to replace the 32 bit lua files with 64 bit if we wish to test or use in 64 bit lua interpreters. 
http://sourceforge.net/projects/luabinaries/files/5.3/Executables/lua-5.3_Win64_bin.zip/download
build option is done ... just adding to distribution install option ie x64 , 
unpack LFW  but swap bins to x64 or x32 depending on user or windows detected 
unpack the goodies from LFW that make it great... 

Anyhow I have no qualms testing... just more modest as programmer. 

just in prior tests of x64 , just swapping binaries seems to work most of the time... 
anyhow at the least i could write a ps1 or batch script for x64 testing....  ie keep LFW but nuke lua x32 bins get zip from sf.net unpack x64 ... 
anyhow ps for updater could be rather simple .. 
I'm Sys-op and security tester , lua python etc, can be useful for audits.
